version: '2'
services:
  mindthecode-springboot:
    build: .
    container_name: mindthecode-springboot
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    links:
      - mysqldb
    networks:
      - main
    depends_on:
      - mysqldb
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.datasource.driverClassName": "com.mysql.jdbc.Driver",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.show-sql": true
        }'
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - main
networks:
  main:
volumes:
  db: